[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Meso-NH"
authors = [{name = "Meso-NH's team", email = "mesonhsupport@utoulouse.fr"}]
dynamic = ["version", "description"]
